name: Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - run: bun run lint
      - run: bun run prettier

      - name: Run app tests
        run: bun run test
        working-directory: ./packages/app
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./packages/app/coverage

      - name: Build app
        run: bun run build
        working-directory: ./packages/app
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./packages/app/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
